title: graswachstum.ch
default_lang: de
author:
  name: 'Martin Zbinden'
  email: martin.zbinden@inforama.ch
taxonomies:
  - category
  - tag
  - author
  - filter
metadata:
  description: AGFF-Grasmessnetzwerk
summary:
  enabled: true
  format: short
  size: 280
  delimiter: '==='
redirects:
  /weideeingaenge: 'https://graswachstum.ch/de/blog/2024-12-weideeingaenge'
  /agff-mb3: /resources/agff-app-fodder-value/index.html
  /ebenrain2025: ''
  /heutrocknung: /resources/agff-app-drycontrol/agff-dry-calc.html
  /apps: 'https://apps.graswachstum.ch/v02'
  /futterwert: 'https://apps.graswachstum.ch/futter'
routes: null
blog:
  route: /home
